import type {
  CameraRecommendation,
  CameraRecommendationPreviewResponse,
  CaseSuggestion,
  EvidenceMediaItem,
  ManualReview,
  TimelineEvent,
} from "../types/api";

export function evidenceMediaFixture(patch: Partial<EvidenceMediaItem> = {}): EvidenceMediaItem {
  return {
    ref: "s3://vigilante-frames/camera-1/frame-001.jpg",
    resolved: true,
    media_id: "media-frame-001",
    media_type: "frame",
    storage_backend: "s3",
    bucket: "vigilante-frames",
    object_key: "camera-1/frame-001.jpg",
    content_type: "image/jpeg",
    size_bytes: 245760,
    width: 1280,
    height: 720,
    captured_at: "2026-01-01T10:00:00Z",
    last_modified_at: "2026-01-01T10:01:00Z",
    camera_id: "camera-1",
    checksum_sha256: "abc123",
    etag: "etag-1",
    content_url: "/api/v1/media/media-frame-001/content",
    thumbnail_url: "/api/v1/media/media-frame-001/thumbnail",
    thumbnail_content_type: "image/jpeg",
    thumbnail_width: 320,
    thumbnail_height: 180,
    thumbnail_available: true,
    thumbnail_status: "available",
    clip_available: true,
    clip_status: "available",
    clip_url: "/api/v1/media/media-frame-001/clip/content",
    clip_content_type: "video/mp4",
    clip_duration_seconds: 1.5,
    clip_frame_count: 3,
    clip_fps: 2,
    clip_width: 1280,
    clip_height: 720,
    metadata_url: "/api/v1/media/media-frame-001",
    metadata: { width: 1280, height: 720 },
    error: null,
    ...patch,
  };
}

export function manualReviewFixture(patch: Partial<ManualReview> = {}): ManualReview {
  return {
    review_id: "review-1",
    source_event_id: "event-1",
    source_event_type: "recognition.manual_review_required",
    review_type: "identity_conflict",
    status: "pending",
    priority: 2,
    severity: "high",
    subject_id: "subject-1",
    track_id: "track-1",
    camera_id: "camera-1",
    organization_id: "org-1",
    site_id: "site-1",
    event_ts: "2026-01-01T10:00:00Z",
    reason_summary: "Identity conflict requires analyst review",
    payload: {
      case_id: "case-1",
      confidence: 0.91,
      evidence_refs: ["s3://vigilante-frames/camera-1/frame-001.jpg"],
      face_detection: { status: "detected", confidence: 0.91 },
      semantic_descriptor: { summary: "person near restricted door" },
    },
    decision: null,
    decision_reason: null,
    resolved_by: null,
    resolved_at: null,
    resolution_payload: {},
    resolution_event_id: null,
    evidence_media: [evidenceMediaFixture()],
    ...patch,
  };
}

export function caseSuggestionFixture(patch: Partial<CaseSuggestion> = {}): CaseSuggestion {
  return {
    suggestion_id: "suggestion-1",
    source_event_id: "event-1",
    source_event_type: "recognition.case_suggestion_created",
    suggestion_type: "unresolved_subject_case",
    status: "pending",
    subject_id: "subject-1",
    track_id: "track-1",
    camera_id: "camera-1",
    organization_id: "org-1",
    site_id: "site-1",
    event_ts: "2026-01-01T10:00:00Z",
    evidence_count: 3,
    reason_summary: "Repeated unresolved subject",
    payload: {
      suggested_title: "Repeated unresolved subject",
      suggested_reason: "Repeated unresolved subject",
      evidence_count: 3,
      evidence_refs: ["s3://vigilante-frames/camera-1/frame-001.jpg"],
      recurrent_subject_assessment: { summary: "three sightings" },
    },
    decision: null,
    decision_reason: null,
    resolved_by: null,
    resolved_at: null,
    resolution_payload: {},
    resolution_event_id: null,
    promoted_case_id: "case-1",
    promoted_at: null,
    evidence_media: [evidenceMediaFixture({ media_id: "media-suggestion-001" })],
    ...patch,
  };
}

export function cameraRecommendationFixture(patch: Partial<CameraRecommendation> = {}): CameraRecommendation {
  return {
    recommendation_id: "rec-face-quality",
    camera_id: "camera-1",
    status: "pending",
    recommendation_type: "face_tuning",
    current_value: { face_quality_threshold: 0.8 },
    suggested_value: { face_quality_threshold: 0.65 },
    evidence: {
      summary: "Face detections dropped below expected volume",
      face_detection: { status: "low_quality", confidence: 0.72 },
      evidence_refs: ["s3://vigilante-frames/camera-1/frame-001.jpg"],
    },
    generated_at: "2026-01-01T10:00:00Z",
    actionable: true,
    applicable: true,
    metadata_paths: ["api.camera.metadata.recognition.face_quality_threshold"],
    impact: "Adjusts recognition face tuning threshold for this camera.",
    severity: "medium",
    title: "Lower face quality threshold",
    reason: "Recent metrics show low quality face detections on camera-1.",
    confidence: 0.84,
    metrics_used: ["face_quality_p50", "face_detection_count"],
    window_summary: { hours: 24, face_quality_p50: 0.52 },
    rule_set_version: "runtime_recommendation_rules_v1",
    source_status: "pending",
    auto_apply: false,
    workflow: {},
    last_error: null,
    ...patch,
  };
}

export function cameraRecommendationPreviewFixture(
  recommendation: CameraRecommendation = cameraRecommendationFixture(),
  patch: Partial<CameraRecommendationPreviewResponse> = {},
): CameraRecommendationPreviewResponse {
  return {
    recommendation,
    applicable: true,
    impact: recommendation.impact,
    patches: [
      {
        metadata_path: "api.camera.metadata.recognition.face_quality_threshold",
        path: ["recognition", "face_quality_threshold"],
        current_value: 0.8,
        current_value_present: true,
        expected_current_value: 0.8,
        expected_current_value_present: true,
        suggested_value: 0.65,
        stale: false,
      },
    ],
    diff: {
      "api.camera.metadata.recognition.face_quality_threshold": {
        from: 0.8,
        to: 0.65,
        current_value_present: true,
      },
    },
    validation_errors: [],
    ...patch,
  };
}

export function timelineEventFixture(patch: Partial<TimelineEvent> = {}): TimelineEvent {
  return {
    source_event_id: "event-1",
    event_type: "case_suggestion_created",
    event_ts: "2026-01-01T10:00:00Z",
    case_id: "case-1",
    camera_id: "camera-1",
    subject_id: "subject-1",
    track_id: "track-1",
    severity: "high",
    confidence: 0.91,
    summary: "Case suggestion created from recognition evidence",
    payload: {
      suggestion_id: "suggestion-1",
      review_id: "review-1",
      confidence: 0.91,
      evidence_refs: ["s3://vigilante-frames/camera-1/frame-001.jpg"],
      source_event: { source_event_id: "event-1", event_type: "recognition" },
    },
    source_component: "vigilante-api",
    organization_id: "org-1",
    site_id: "site-1",
    evidence_media: [evidenceMediaFixture({ media_id: "media-timeline-001" })],
    ...patch,
  };
}
