import { formatDateTime } from "./format";
import type { ReactNode } from "react";

export interface MetadataRow {
  label: string;
  value: ReactNode;
}

export function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

export function asRecord(value: unknown): Record<string, unknown> | null {
  return isRecord(value) ? value : null;
}

export function payloadValue(payload: Record<string, unknown>, key: string): unknown {
  if (payload[key] !== undefined) {
    return payload[key];
  }

  const sourceEvent = asRecord(payload.source_event);
  if (sourceEvent && sourceEvent[key] !== undefined) {
    return sourceEvent[key];
  }

  return undefined;
}

export function payloadString(payload: Record<string, unknown> | null | undefined, keys: string[]): string | null {
  if (!payload) {
    return null;
  }

  for (const key of keys) {
    const value = payloadValue(payload, key);
    if (typeof value === "string" && value.trim()) {
      return value;
    }
    if (typeof value === "number" || typeof value === "boolean") {
      return String(value);
    }
  }

  return null;
}

export function summarizeValue(value: unknown): string {
  if (value === null || value === undefined || value === "") {
    return "—";
  }

  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  if (Array.isArray(value)) {
    const first = value[0];
    if (value.length === 0) {
      return "0 items";
    }
    if (typeof first === "string" || typeof first === "number") {
      return value.slice(0, 4).join(", ");
    }
    return `${value.length} item${value.length === 1 ? "" : "s"}`;
  }

  if (isRecord(value)) {
    const preferred = ["summary", "label", "description", "reason", "status", "confidence", "score", "decision_reason"]
      .map((key) => value[key])
      .find((item) => item !== undefined && item !== null);
    if (preferred !== undefined) {
      return summarizeValue(preferred);
    }
    return Object.keys(value).slice(0, 5).join(", ") || "object";
  }

  return String(value);
}

export function evidenceHighlights(payload: Record<string, unknown>): MetadataRow[] {
  const rows: MetadataRow[] = [];
  const keys = [
    ["Confidence", ["confidence", "match_confidence", "score"]],
    ["Evidence count", ["evidence_count"]],
    ["Severity", ["severity"]],
    ["Decision reason", ["decision_reason", "reason_summary", "suggested_reason"]],
    ["Generated by", ["source_component", "generator", "model"]],
  ] as const;

  keys.forEach(([label, lookupKeys]) => {
    const value = payloadString(payload, [...lookupKeys]);
    if (value) {
      rows.push({ label, value });
    }
  });

  return rows;
}

export function sourceEventMetadata(value: unknown): MetadataRow[] {
  const sourceEvent = asRecord(value);
  if (!sourceEvent) {
    return [];
  }

  const rows: MetadataRow[] = [];
  const entries = [
    ["Event ID", sourceEvent.source_event_id ?? sourceEvent.event_id],
    ["Event type", sourceEvent.event_type ?? sourceEvent.type],
    ["Event time", formatDateTime((sourceEvent.event_ts ?? sourceEvent.timestamp ?? sourceEvent.created_at) as string | null | undefined)],
    ["Camera", sourceEvent.camera_id],
    ["Subject", sourceEvent.subject_id],
    ["Track", sourceEvent.track_id],
    ["Organization", sourceEvent.organization_id],
    ["Site", sourceEvent.site_id],
  ];

  entries.forEach(([label, value]) => {
    if (value !== undefined && value !== null && value !== "—") {
      rows.push({ label: String(label), value: summarizeValue(value) });
    }
  });

  return rows;
}
